#!/bin/bash
for file1 in /home/viorik/Work/SVNRepository/trunk/EvaluationDataset/RealImages/pgm/*.pgm 
do
echo $file1
bn=$(basename $file1)
fn=${bn%.*}
file2="/home/viorik/Work/SVNRepository/trunk/EvaluationDataset/RealImages/pgm/result/$fn.svg"
file3="/home/viorik/Work/SVNRepository/trunk/EvaluationDataset/RealImages/pgm/result/$fn.pgm"
file4="/home/viorik/Work/SVNRepository/trunk/EvaluationDataset/RealImages/pgm/result/$fn.png"
./elsdc $file1 "/media/MYPASSPORT/tmp.txt"
convert "output.svg" $file4
mv "output.svg" $file2
mv "labels.pgm" $file3
rm "/media/MYPASSPORT/tmp.txt"
done
