#!/bin/bash
for file1 in /home/viorik/Work/SVNRepository/trunk/EvaluationDataset/pureNoise/*.pgm 
do
echo $file1
bn=$(basename $file1)
fn=${bn%.*}
file2="/media/MYPASSPORT/ELSDc/pure/$fn.svg"
file3="/media/MYPASSPORT/ELSDc/pure/$fn.png"
file4="/media/MYPASSPORT/ELSDc/pure/$fn.txt"
file5="/media/MYPASSPORT/ELSDc/pure/$fn.pgm"
file6="/media/MYPASSPORT/ELSDc/pure1/$fn.txt"
./elsdc $file1 "/media/MYPASSPORT/tmp.txt"
convert "output.svg" $file3
mv "output.svg" $file2
mv "labels.pgm" $file5
mv "out_ellipse.txt" $file4
mv "out_polygon.txt" $file6
rm "/media/MYPASSPORT/tmp.txt"
done
