#!/bin/bash
for file1 in /home/viorik/Work/SVNRepository/trunk/EvaluationDataset/CalibrationPatterns/TestRealImage/all/pgm/*.pgm 
do
echo $file1
bn=$(basename $file1)
fn=${bn%.*}
file2="/home/viorik/Work/SVNRepository/trunk/EvaluationDataset/CalibrationPatterns/TestRealImage/all/ELSDc/resultsvg/$fn.svg"
file3="/home/viorik/Work/SVNRepository/trunk/EvaluationDataset/CalibrationPatterns/TestRealImage/all/ELSDc/resultpng/$fn.png"
file4="/home/viorik/Work/SVNRepository/trunk/EvaluationDataset/CalibrationPatterns/TestRealImage/all/ELSDc/resulttxt/$fn.txt"
file5="/home/viorik/Work/SVNRepository/trunk/EvaluationDataset/CalibrationPatterns/TestRealImage/all/ELSDc/resultpgm/$fn.pgm"
file6="/home/viorik/Work/SVNRepository/trunk/EvaluationDataset/CalibrationPatterns/TestRealImage/all/ELSDc/resulttxt_poly/$fn.txt"
./elsdc $file1 "/home/viorik/tmp.txt"
convert "output.svg" $file3
mv "output.svg" $file2
mv "labels.pgm" $file5
mv "out_ellipse.txt" $file4
mv "out_polygon.txt" $file6
done
